### PR TITLE
Migrate to compiler tracers

### LINKED ISSUE #1: Incompatible with Elixir 1.10?
```
== Compilation error in file lib/mix_unused.ex ==
** (CompileError) lib/mix_unused.ex:55: cannot import Mix.Compilers.Elixir.read_manifest/2 because it is undefined or private
    (elixir 1.10.2) src/elixir_import.erl:64: :elixir_import.calculate/6
    (elixir 1.10.2) src/elixir_import.erl:18: :elixir_import.import/4
```
@hauleth, any chance of an update?  This seems to be the only dep out there to provide dead code detection.

### PR DESCRIPTION
**Pull request by hauleth**
- [x] use Elixir compilation tracing, this will make this project Elixir 1.10+ only
- [x] allow defining ignored functions
- [x] implement CLI options (severity)
- [x] implement caching of the results for recompilation purposes
- [x] do not report behaviour callbacks

Close #1

### CODE REVIEW

**Comment by tensiondriven** [comment]
I checked out this branch by adding it to my project mix.exs with the branch: flag and confirmed the hash in mix.lock matched the hash of the PR.  I’m running Elixir 1.10.x in my mix.exs.

I tried running the mix task with

mix compile.unused

And regardless of parameters, I get no output.

Any tips for testing this?  I’m not at my computer right now but can provide more details later.  It also occurs to me that I could try running the test suite to see how I can get it to run against my project.

Any tips would be appreciated!

**Comment by hauleth** [comment]
From what I see it will currently work only if there will be full recompilation of the project. I will update docs and I am currently working on manifest storage.

**Comment by tensiondriven** [comment]
I tried running this again, and I still don't get any output.  I think something may be wrong with how it is getting invoked, or how my app works with it.

Here's a diff of mix.exs and mix.lock which shows the dep being added:

```
diff --git a/mix.exs b/mix.exs
index 44a14c25..a1332e64 100644
--- a/mix.exs
+++ b/mix.exs
@@ -69,7 +69,8 @@ defmodule Tealdog.MixProject do
       {:ex_unit_notifier, "~> 0.1", only: :test},
       {:phoenix_slime, "~> 0.13.1"},
       {:httpoison, "~> 1.6"},
-      {:shorter_maps, "~> 2.1.0"}
+      {:shorter_maps, "~> 2.1.0"},
+      {:mix_unused, github: "hauleth/mix_unused", branch: "ft/migrate-to-compiler-tracers"}
     ]
   end

diff --git a/mix.lock b/mix.lock
index c257d7d9..782947fd 100644
--- a/mix.lock
+++ b/mix.lock
@@ -31,6 +31,7 @@
   "mime": {:hex, :mime, "1.3.1", "30ce04ab3175b6ad0bdce0035cba77bba68b813d523d1aac73d9781b4d193cf8", [:mix], [], "hexpm", "6cbe761d6a0ca5a31a0931bf4c63204bceb64538e664a8ecf784a9a6f3b875f1"},
   "mimerl": {:hex, :mimerl, "1.2.0", "67e2d3f571088d5cfd3e550c383094b47159f3eee8ffa08e64106cdf5e981be3", [:rebar3], [], "hexpm", "f278585650aa581986264638ebf698f8bb19df297f66ad91b18910dfc6e19323"},
   "mix_test_watch": {:hex, :mix_test_watch, "1.0.2", "34900184cbbbc6b6ed616ed3a8ea9b791f9fd2088419352a6d3200525637f785", [:mix], [{:file_system, "~> 0.2.1 or ~> 0.3", [hex: :file_system, repo: "hexpm", optional: false]}], "hexpm", "47ac558d8b06f684773972c6d04fcc15590abdb97aeb7666da19fcbfdc441a07"},
+  "mix_unused": {:git, "https://github.com/hauleth/mix_unused.git", "4be00d4b1a51d2f7caf221c075d5d6cc9023bcec", [branch: "ft/migrate-to-compiler-tracers"]},
   "nanoid": {:hex, :nanoid, "2.0.2", "f3f7b4bf103ab6667f22beb00b6315825ee3f30100dd2c93d534e5c02164e857", [:mix], [], "hexpm", "3095cb1fac7bbc78843a8ccd99f1af375d0da1d3ebaa8552e846b73438c0c44f"},
   "neotoma": {:hex, :neotoma, "1.7.3", "d8bd5404b73273989946e4f4f6d529e5c2088f5fa1ca790b4dbe81f4be408e61", [:rebar], [], "hexpm", "2da322b9b1567ffa0706a7f30f6bbbde70835ae44a1050615f4b4a3d436e0f28"},
   "oauth2": {:hex, :oauth2, "2.0.0", "338382079fe16c514420fa218b0903f8ad2d4bfc0ad0c9f988867dfa246731b0", [:mix], [{:hackney, "~> 1.13", [hex: :hackney, repo: "hexpm", optional: false]}], "hexpm", "881b8364ac7385f9fddc7949379cbe3f7081da37233a1aa7aab844670a91e7e7"},
```

Then, I went into `deps/mix_unused` and added puts:

image


Finally, I ran `rm -rf _build ; mix compile.unused`. This is the output I got:

```
$ rm -rf _build ; mix compile.unused
....
Generated ueberauth_google app
==> phoenix_ecto
Compiling 7 files (.ex)
Generated phoenix_ecto app
MixUnused.Tracer: start_link()
MixUnused.Tracer: init()
Mix.Tasks.Compile.Unused: run()
```

So, if I `compile.unused`, the app gets build, and the dep gets run, but doesn't produce any output.

I also added an unused function here, to ensure that I have some unused code (though I'm sure there's much more):

```
diff --git a/lib/tealdog.ex b/lib/tealdog.ex
index ceabfad6..fae07ecf 100644
--- a/lib/tealdog.ex
+++ b/lib/tealdog.ex
@@ -6,4 +6,8 @@ defmodule Tealdog do
   Contexts are also responsible for managing your data, regardless
   if it comes from the database, an external API or others.
   """
+
+  def not_used do
+    "Foobar"
+  end
 end
```

Any pointers?

**Comment by hauleth** [comment]
You need to update compiler list:

```elixir
compilers: [:unused | Mix.compilers()]
```

In your `mix.exs` in similar way to the boundary as this needs to gather data during compilation of the project and will display messages only after `mix compile.app`.

**Comment by sickill** [comment]
Same here on Erlang 22.3.4.3, Elixir 1.10.4. I have `:unused` added to compilers list, I've `rm -rf _build/dev`, ran `mix compile.unused`, and other than the usual compiler output I got nothing.

**Comment by hauleth** [comment]
@sickill I have recently not that much time to spare to work on this. I will update as soon as I will find some time to do so.

**Comment by sickill** [comment]
No worries! Just adding a data point. No rush at all.

**Comment by hauleth** [comment]
@sickill @tensiondriven do you have apps that I can test on?

**Comment by tensiondriven** [comment]
I'm afraid not, just one monolith that I can't really share.  If I get back
to working with mix_unused and can find a simple repro case, I'll share it
for sure.
ᐧ

**Comment by hauleth** [comment]
NVM, I have found the reason and I will push the update soon.

In short - I thought that Mix will print diagnostics for me, which happens to not be true. So I will provide update soon, with messages being printed.

**Pull request merged**
